# Generated by Django 5.2.17 on 2026-09-27 20:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_access', '0003_workspace_network_and_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='vncaccessgrant',
            name='target_socket',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='vncworkspace',
            name='controller_schema',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vncworkspace',
            name='vnc_socket',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='vncaccessgrant',
            name='target_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkspaceApplicationLaunch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_name', models.CharField(max_length=255)),
                ('request_id', models.CharField(max_length=255, unique=True)),
                ('runtime_id', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_launches', to='station_access.vncworkspace')),
            ],
        ),
    ]
