# Planning metadata only. Not a package recipe or dependency-resolver input.
{'schema': 1,
 'profile': 'foreign-kernel-host-v1',
 'architecture': 'x86_64',
 'status': 'planning-not-installable',
 'dependency_closure': 'not-reviewed',
 'items': [
  {'project': 'glibc', 'role': 'C runtime and dynamic loader', 'group': 'base'},
  {'project': 'bash', 'role': 'shell for host initialization', 'group': 'base'},
  {'project': 'coreutils', 'role': 'base file and process utilities', 'group': 'base'},
  {'project': 'util-linux', 'role': 'mounting and block-device utilities; review disabled features', 'group': 'base'},
  {'project': 'shadow', 'role': 'accounts and emergency login policy; review required subset', 'group': 'base'},
  {'project': 'systemd', 'role': 'PID 1, journald, udev and proposed networkd/resolved services', 'group': 'host'},
  {'project': 'openssl', 'role': 'TLS library for rebuilt Python', 'group': 'next-compilation'},
  {'project': 'sqlite', 'role': 'SQL library for rebuilt Python', 'group': 'next-compilation'},
  {'project': 'python', 'role': 'rebuild and require ssl/_ssl and sqlite3/_sqlite3 acceptance', 'group': 'next-compilation'},
  {'project': 'ca-certificates', 'role': 'review authoritative trust-store source and update policy', 'group': 'host'},
  {'project': 'iproute2', 'role': 'network diagnostics and administration', 'group': 'host'},
  {'project': 'kmod', 'role': 'module loading support for matching foreign kernel', 'group': 'host'},
  {'project': 'dbus', 'role': 'candidate system bus provider; confirm service requirements', 'group': 'selection-review'},
  {'project': 'host-identify', 'role': 'host Ed25519 identity primitives; fresh state at first boot', 'group': 'zog'},
  {'project': 'host-discover', 'role': 'enrollment, beacon and control transport', 'group': 'zog'},
  {'project': 'box-control', 'role': 'trusted local lifecycle and root-control installation contract', 'group': 'zog'},
  {'project': 'linux', 'role': 'current API headers only; first kernel/initramfs/modules remain foreign', 'group': 'foreign-boot'},
 ],
 'recipe_review_candidates': ['meson', 'ninja', 'gperf', 'libcap', 'libseccomp',
                              'jinja2', 'packaging', 'pyelftools'],
 'candidate_note': 'Review selected upstream build options before adding dependency edges; this list is not a required closure.',
 'acceptance': ['self-hosted compiler acceptance', 'PID 1 and controller service startup',
                'TLS certificate verification', 'Python SSL and SQLite modules',
                'DHCP/DNS and outbound enrollment', 'fresh host identity in persistent state',
                'read-only host with writable state and applications',
                'foreign initramfs root/state mounting', 'authenticated control operation'],
 'excluded_from_first_host': ['station-access server', 'X11', 'TurboVNC',
                             'Zog-built kernel', 'Secure Boot', 'TPM attestation']}
