# Data only; parsed with ast.literal_eval.
{'project': 'tcl',
 'stage_id': 'final',
 'version': '8.6.18',
 'reference': 'https://www.linuxfromscratch.org/lfs/view/13.1-systemd/chapter08/tcl.html',
 'test_policy': 'Mandatory upstream tests. Unexpected results stop the graph; no automatic '
                'known-failure waiver.',
 'bootstrap_contract': 'Verified source-built final-libc root. Compiler replacements require '
                       'recorded old-file ownership.',
 'bundled_packages': {'included': ['itcl4.3.7',
                                   'sqlite3.53.0',
                                   'tdbc1.1.13',
                                   'tdbcsqlite3-1.1.13',
                                   'thread2.8.13'],
                      'excluded': {'tdbcmysql1.1.13': ['MySQL client library and test '
                                                       'database'],
                                   'tdbcodbc1.1.13': ['ODBC driver manager, drivers and test '
                                                      'databases'],
                                   'tdbcpostgres1.1.13': ['PostgreSQL client library and test '
                                                          'database']}},
 'test_environment': {'accounts': 'Controller execution UID/GID mapped to build-user; root '
                                  'and nobody are explicit fixtures.',
                      'home': '/tmp (writable controller workspace)',
                      'locale': 'C.UTF-8 generated by source-built Glibc localedef',
                      'features': 'Core and all included extensions are built, tested and '
                                  'installed. Excluded database adapters are absent from '
                                  'build and install, not failed tests waived.'}}
