# Data only; parsed with ast.literal_eval.
{'schema': 1,
 'profiles': {'amazon-linux-2023': {'related_packages': ['sqlite',
                                                         'sqlite-devel'],
                                    'seed_packages': [],
                                    'status': 'unreviewed',
                                    'review_notes': 'name-mapping-not-installed-or-live-verified',
                                    'seed_required': False},
              'fedora-rawhide': {'related_packages': ['sqlite', 'sqlite-devel'],
                                 'seed_packages': [],
                                 'status': 'unreviewed',
                                 'review_notes': 'spec-reviewed',
                                 'seed_required': False},
              'opensuse-tumbleweed': {'related_packages': ['sqlite3',
                                                           'sqlite3-devel'],
                                      'seed_packages': [],
                                      'status': 'unreviewed',
                                      'review_notes': 'spec-reviewed',
                                      'seed_required': False}}}
