# Data only; parsed with ast.literal_eval.
{'schema': 1,
 'runtime_requirements': ['cryptography>=36.0.2',
                          "build; extra == 'tests'",
                          "coverage; extra == 'tests'",
                          "flake8; extra == 'tests'",
                          "mypy; extra == 'tests'",
                          "requests; extra == 'tests'",
                          "ruff; extra == 'tests'",
                          "wheel; extra == 'tests'"],
 'build_system': {'requires': ['hatchling', 'hatch-vcs'], 'build-backend': 'hatchling.build'},
 'runtime_packages': ['python-cryptography'],
 'blockers': [],
 'sources': [{'url': 'https://files.pythonhosted.org/packages/80/95/083707b15af3bdbb6c9e54ae7f448046f7ab55f9eaa5cccdc5dd23791d15/http_message_signatures-2.0.1.tar.gz',
              'sha256': '394545b0cc296a4fd45166f57056e7e029dcd5b91d9bf549e108c96c23aa1cba',
              'destination': 'upstream',
              'archive': True}],
 'status': 'not-authored',
 'notes': ['Execution uses final stage on the accepted cryptography base; tests extras are not '
           'runtime requirements.']}
