# Generated by Django 5.2.17 on 2026-09-27 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host_registry', '0009_cloud_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_revision', models.PositiveBigIntegerField()),
                ('observed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=24)),
                ('serving', models.BooleanField(default=False)),
                ('lease_expires_at', models.PositiveBigIntegerField(null=True)),
                ('summary', models.JSONField(default=dict)),
                ('preparation', models.JSONField(default=dict)),
                ('total', models.PositiveIntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='host_registry.host')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('collection', models.CharField(max_length=64)),
                ('digest', models.CharField(max_length=64)),
                ('metadata', models.JSONField()),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='archive_inventory.observation')),
            ],
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['host', 'complete', '-observed_at'], name='archive_inv_host_id_b8c0b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('observation', 'position'), name='archive_observation_position'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('observation', 'collection', 'digest'), name='archive_observation_content'),
        ),
    ]
