"""Deterministic composition of package-provided GNU Info menu contributions.

Only usr/share/info/dir has this policy. Ordinary ownership conflicts remain
errors. Unknown menu syntax and conflicting definitions are never discarded.
"""
import re
from .errors import ImageBuildError

POLICY = 'info-menu-union-v1'
PATH = 'usr/share/info/dir'
HEADER = 'Generated by image-build from recorded package Info indexes.\n\x1f\nFile: dir,  Node: Top\n\n* Menu:\n'


def entries(text):
    lines = text.split('\n')
    menus = [i for i, line in enumerate(lines) if line.rstrip() == '* Menu:']
    if len(menus) != 1 or '\x1f' not in text:
        raise ImageBuildError('unsupported Info directory header')
    result = {}; section = None; entry = []

    def flush():
        if not entry:
            return
        match = re.match(r'^\* ([^:]+):\s+(\([^\)]+\)[^.]*\.)', entry[0])
        if section is None or not match:
            raise ImageBuildError('unsupported Info directory entry')
        key = (section, match[1], match[2]); value = '\n'.join(entry)
        if key in result and result[key] != value:
            raise ImageBuildError('conflicting Info entry: ' + str(key))
        result[key] = value
        entry.clear()

    for line in lines[menus[0]+1:]:
        line = line.rstrip()
        if not line:
            flush()
        elif line.startswith('* '):
            flush(); entry.append(line)
        elif line[0].isspace():
            if not entry:
                raise ImageBuildError('orphan Info entry continuation')
            entry.append(line)
        else:
            flush()
            if any(ord(c) < 32 for c in line):
                raise ImageBuildError('unsupported Info directory control character')
            section = line
    flush()
    return result


def compose(*texts):
    merged = {}
    for text in texts:
        for key, value in entries(text).items():
            if key in merged and merged[key] != value:
                raise ImageBuildError('conflicting Info entry: ' + str(key))
            merged[key] = value
    output = [HEADER]
    for section in sorted({key[0] for key in merged}):
        output.append('\n'+section+'\n')
        output.extend(merged[key]+'\n' for key in sorted(merged) if key[0] == section)
    return ''.join(output)
