# Generated by Django 5.2.17 on 2026-09-19 17:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=120, unique=True)),
                ('last_attempt', models.DateTimeField(null=True)),
                ('last_success', models.DateTimeField(null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('instance_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('provider', models.CharField(default='generic', max_length=20)),
                ('account_id', models.CharField(blank=True, max_length=32)),
                ('region', models.CharField(blank=True, max_length=40)),
                ('instance_id', models.CharField(blank=True, max_length=80)),
                ('workspace_id', models.CharField(blank=True, max_length=80)),
                ('token_digest', models.CharField(blank=True, max_length=64)),
                ('token_revoked', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_received', models.DateTimeField(blank=True, null=True)),
                ('report', models.JSONField(default=dict)),
                ('aws_observation', models.JSONField(default=dict)),
                ('aws_checked_at', models.DateTimeField(blank=True, null=True)),
                ('aws_missing_since', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['label', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider', 'aws')), fields=('account_id', 'region', 'instance_id'), name='unique_aws_host')],
            },
        ),
    ]
