# Generated by Django 5.2.17 on 2026-09-20 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsAssignment',
            fields=[
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='dns_assignment', serialize=False, to='host_registry.host')),
                ('name', models.CharField(max_length=253, unique=True)),
                ('owner_id', models.CharField(editable=False, max_length=256, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('desired_action', models.CharField(default='waiting', max_length=20)),
                ('desired_address', models.CharField(blank=True, max_length=45)),
                ('applied_revision', models.PositiveBigIntegerField(null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('record_id', models.CharField(blank=True, max_length=80)),
                ('observed_address', models.CharField(blank=True, max_length=45)),
                ('last_attempt', models.DateTimeField(null=True)),
                ('last_success', models.DateTimeField(null=True)),
                ('last_change', models.DateTimeField(null=True)),
                ('next_attempt', models.DateTimeField(null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('error', models.CharField(blank=True, max_length=1000)),
                ('last_action', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
