# Generated by Django 5.2.17 on 2026-09-23 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_registry', '0002_dnsassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionWindow',
            fields=[
                ('bucket', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivePolicy',
            fields=[
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='host_registry.host')),
                ('operations', models.JSONField(default=list)),
                ('collections', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('fingerprint', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('public_key', models.CharField(max_length=44)),
                ('claims', models.JSONField(default=dict)),
                ('claimed_host_id', models.CharField(blank=True, max_length=36)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=40)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('host_id_text', models.CharField(blank=True, max_length=36)),
                ('details', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityGate',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='legacy_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='signed_last_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReplayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64)),
                ('nonce', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fingerprint', 'nonce'), name='unique_signed_request')],
            },
        ),
        migrations.CreateModel(
            name='HostIdentity',
            fields=[
                ('fingerprint', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('public_key', models.CharField(max_length=44)),
                ('status', models.CharField(default='approved', max_length=16)),
                ('approved_by', models.CharField(max_length=150)),
                ('approved_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identities', to='host_registry.host')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('host',), name='one_approved_key_per_host')],
            },
        ),
    ]
