# Generated by Django 5.2.17 on 2026-09-25 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_registry', '0004_security_gate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirrorRole',
            fields=[
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='mirror_role', serialize=False, to='host_registry.host')),
                ('selected', models.BooleanField(default=False)),
                ('endpoint', models.CharField(blank=True, max_length=253)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('changed_at', models.DateTimeField()),
                ('acknowledged_revision', models.PositiveBigIntegerField(default=0)),
                ('reported_state', models.CharField(default='assigned', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=60)),
                ('runtime_id', models.CharField(blank=True, max_length=120)),
                ('observed_at', models.DateTimeField(null=True)),
                ('last_ready_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationCredential',
            fields=[
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='host_registry.host')),
                ('key_id', models.CharField(max_length=80)),
                ('ciphertext', models.TextField()),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('changed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
            ],
        ),
    ]
