# Generated by Django 5.2.17 on 2026-09-27 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_registry', '0006_host_archival'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeaconDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=300, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('ca_certificate', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=20)),
                ('account_id', models.CharField(blank=True, max_length=32)),
                ('key_id', models.CharField(max_length=80)),
                ('ciphertext', models.TextField()),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DnsProviderSelection',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('credential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='host_registry.providercredential')),
            ],
        ),
    ]
