# Generated by Django 5.2.17 on 2026-09-27 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_registry', '0007_setup_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAccessCheck',
            fields=[
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='access_check', serialize=False, to='host_registry.providercredential')),
                ('credential_revision', models.PositiveIntegerField()),
                ('attempt_id', models.UUIDField(default=uuid.uuid4)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='checking', max_length=24)),
                ('domains', models.JSONField(default=list)),
                ('more_available', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
