# Generated by Django 5.2.17 on 2026-09-27 18:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_registry', '0008_provider_access_checks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('account_id', models.CharField(max_length=12)),
                ('mode', models.CharField(max_length=16)),
                ('region', models.CharField(default='us-east-1', max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('key_id', models.CharField(blank=True, max_length=80)),
                ('ciphertext', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_revision', models.PositiveIntegerField(default=0)),
                ('check_attempt', models.UUIDField(null=True)),
                ('check_started_at', models.DateTimeField(null=True)),
                ('check_finished_at', models.DateTimeField(null=True)),
                ('check_status', models.CharField(default='never', max_length=24)),
            ],
        ),
    ]
