# Generated by Django 5.2.17 on 2026-09-29 19:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_registry', '0009_cloud_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=16)),
                ('state', models.CharField(default='queued', max_length=16)),
                ('actor', models.CharField(max_length=150)),
                ('request', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('command_id', models.CharField(blank=True, max_length=80)),
                ('command_ids', models.JSONField(default=list)),
                ('checking_outcome', models.BooleanField(default=False)),
                ('attempt_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployment_jobs', to='host_registry.host')),
            ],
        ),
    ]
