# Generated by Django 5.2.17 on 2026-10-03 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_registry', '0012_managed_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsDestination',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('selection', models.JSONField()),
                ('ledger_path', models.CharField(max_length=500)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalDnsAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(default='ready', max_length=20)),
                ('name', models.CharField(max_length=253, unique=True)),
                ('owner_id', models.CharField(editable=False, max_length=256)),
                ('enabled', models.BooleanField(default=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('desired_action', models.CharField(default='waiting', max_length=20)),
                ('desired_address', models.CharField(blank=True, max_length=45)),
                ('applied_revision', models.PositiveBigIntegerField(null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('record_id', models.CharField(blank=True, max_length=80)),
                ('observed_address', models.CharField(blank=True, max_length=45)),
                ('last_attempt', models.DateTimeField(null=True)),
                ('last_success', models.DateTimeField(null=True)),
                ('last_change', models.DateTimeField(null=True)),
                ('next_attempt', models.DateTimeField(null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('error', models.CharField(blank=True, max_length=1000)),
                ('last_action', models.CharField(blank=True, max_length=30)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additional_dns_assignments', to='host_registry.host')),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='host_registry.dnsdestination')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('host', 'binding'), name='unique_additional_dns_host_binding')],
            },
        ),
    ]
