# Data only; parsed with ast.literal_eval.
{'project': 'python-setuptools',
 'stage_id': 'final',
 'base_contract': 'Accepted CPython 3.15 self-hosted root with OpenSSL, SQLite '
                  'and libffi development files.',
 'python_distribution': 'setuptools',
 'version': '84.0.0',
 'build_system': {'requires': [],
                  'build-backend': 'setuptools.build_meta',
                  'backend-path': ['.']},
 'runtime_requirements': ['pytest!=8.1.*,>=6; extra == "test"',
                          'virtualenv>=13.0.0; extra == "test"',
                          'wheel>=0.44.0; extra == "test"',
                          'pip>=19.1; extra == "test"',
                          'packaging>=24.2; extra == "test"',
                          'jaraco.envs>=2.2; extra == "test"',
                          'pytest-xdist>=3; extra == "test"',
                          'jaraco.path>=3.7.2; extra == "test"',
                          'build[virtualenv]>=1.0.3; extra == "test"',
                          'filelock>=3.4.0; extra == "test"',
                          'ini2toml[lite]>=0.14; extra == "test"',
                          'tomli-w>=1.0.0; extra == "test"',
                          'pytest-timeout; extra == "test"',
                          'pytest-perf; sys_platform != "cygwin" and extra == '
                          '"test"',
                          'jaraco.develop>=7.21; (python_version >= "3.9" and '
                          'sys_platform != "cygwin") and extra == "test"',
                          'pytest-home>=0.5; extra == "test"',
                          'pytest-subprocess; extra == "test"',
                          'pyproject-hooks!=1.1; extra == "test"',
                          'jaraco.test>=5.5; extra == "test"',
                          'sphinx>=3.5; extra == "doc"',
                          'jaraco.packaging>=9.3; extra == "doc"',
                          'rst.linker>=1.9; extra == "doc"',
                          'furo; extra == "doc"',
                          'sphinx-lint; extra == "doc"',
                          'jaraco.tidelift>=1.4; extra == "doc"',
                          'pygments-github-lexers==0.0.5; extra == "doc"',
                          'sphinx-favicon; extra == "doc"',
                          'sphinx-inline-tabs; extra == "doc"',
                          'sphinx-reredirects; extra == "doc"',
                          'sphinxcontrib-towncrier; extra == "doc"',
                          'sphinx-notfound-page<2,>=1; extra == "doc"',
                          'pyproject-hooks!=1.1; extra == "doc"',
                          'towncrier<24.7; extra == "doc"',
                          'packaging>=24.2; extra == "core"',
                          'more_itertools>=8.8; extra == "core"',
                          'jaraco.text>=3.7; extra == "core"',
                          'importlib_metadata>=6; python_version < "3.10" and '
                          'extra == "core"',
                          'tomli>=2.0.1; python_version < "3.11" and extra == '
                          '"core"',
                          'wheel>=0.43.0; extra == "core"',
                          'jaraco.functools>=4; extra == "core"',
                          'more_itertools; extra == "core"',
                          'pytest-checkdocs>=2.14; extra == "check"',
                          'pytest-ruff>=0.2.1; sys_platform != "cygwin" and '
                          'extra == "check"',
                          'ruff>=0.13.0; sys_platform != "cygwin" and extra == '
                          '"check"',
                          'pytest-cov; extra == "cover"',
                          'pytest-enabler>=3.4; extra == "enabler"',
                          'pytest-mypy>=1.0.1; platform_python_implementation '
                          '!= "PyPy" and extra == "type"',
                          'mypy==1.18.*; extra == "type"',
                          'importlib_metadata>=7.0.2; python_version < "3.10" '
                          'and extra == "type"',
                          'jaraco.develop>=7.21; sys_platform != "cygwin" and '
                          'extra == "type"'],
 'patches': [],
 'patches_complete': True,
 'test_scope': 'Wheel integrity, isolated installed imports and targeted '
               'behavior; complete upstream optional test suites are not run '
               'in this stage.',
 'source_omissions': {'reason': 'Linux-only target; do not install upstream '
                                'precompiled Windows launchers. Source archive '
                                'retained unchanged.',
                      'files': [{'path': 'setuptools-84.0.0/setuptools/cli-32.exe',
                                 'sha256': '32acc1bc543116cbe2cff10cb867772df2f254ff2634c870aef0b46c4b696fdb'},
                                {'path': 'setuptools-84.0.0/setuptools/cli-64.exe',
                                 'sha256': 'bbb3de5707629e6a60a0c238cd477b28f07f0066982fda953fa6fcec39073a4a'},
                                {'path': 'setuptools-84.0.0/setuptools/cli-arm64.exe',
                                 'sha256': 'b9a7d08da880dfac8bcf548eba4b06fb59b6f09b17d33148a0f6618328926c61'},
                                {'path': 'setuptools-84.0.0/setuptools/cli.exe',
                                 'sha256': '32acc1bc543116cbe2cff10cb867772df2f254ff2634c870aef0b46c4b696fdb'},
                                {'path': 'setuptools-84.0.0/setuptools/gui-32.exe',
                                 'sha256': '85dae1e95d77845f2cb59bcac3d4afe74bbe4c91a9bcc5bf4a71cd43104dbe7c'},
                                {'path': 'setuptools-84.0.0/setuptools/gui-64.exe',
                                 'sha256': '3471b6140eadc6412277dbbefe3fef8c345a0f1a59776086b80a3618c3a83e3b'},
                                {'path': 'setuptools-84.0.0/setuptools/gui-arm64.exe',
                                 'sha256': 'e694f4743405c8b5926ff457db6fe7f1a12dec7c16a9c3864784d3f4e07ae097'},
                                {'path': 'setuptools-84.0.0/setuptools/gui.exe',
                                 'sha256': '85dae1e95d77845f2cb59bcac3d4afe74bbe4c91a9bcc5bf4a71cd43104dbe7c'}]}}
