# Generated by Django 5.2.17 on 2026-09-25 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=64)),
                ('digest', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('kind', models.CharField(max_length=32)),
                ('managed', models.BooleanField(default=False)),
                ('provenance', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('collection', 'digest'), name='mirror_collection_digest')],
            },
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_mirror.archive')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('archive', 'name'), name='mirror_archive_pin')],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=128)),
                ('month', models.CharField(max_length=7)),
                ('commit', models.CharField(max_length=64)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive_mirror.archive')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'month'), name='mirror_source_month')],
            },
        ),
    ]
