# Generated by Django 5.2.17 on 2026-09-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_mirror', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionStatus',
            fields=[
                ('source', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('last_attempt', models.DateTimeField()),
                ('last_success', models.DateTimeField(null=True)),
                ('error', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
