# Data only; parsed with ast.literal_eval.
{'schema': 1,
 'architecture': 'x86_64',
 'stages': [{'id': 'util-linux-nologin',
             'project': 'util-linux',
             'stage': 'nologin',
             'recipe': 'util-linux/stages/nologin'},
            {'id': 'dbus-final',
             'project': 'dbus',
             'stage': 'final',
             'recipe': 'dbus/stages/final'},
            {'id': 'iproute2-final',
             'project': 'iproute2',
             'stage': 'final',
             'recipe': 'iproute2/stages/final'},
            {'id': 'libseccomp-final',
             'project': 'libseccomp',
             'stage': 'final',
             'recipe': 'libseccomp/stages/final'},
            {'id': 'e2fsprogs-final',
             'project': 'e2fsprogs',
             'stage': 'final',
             'recipe': 'e2fsprogs/stages/final'}],
 'targets': ['util-linux-nologin',
             'dbus-final',
             'iproute2-final',
             'libseccomp-final',
             'e2fsprogs-final']}
