# Data only; parsed with ast.literal_eval.
{'schema': 1,
 'lfs_edition': '13.1-systemd',
 'architecture': 'x86_64',
 'build': 'x86_64-pc-linux-gnu',
 'target': 'x86_64-zog-linux-gnu',
 'stages': [{'id': 'binutils-cross-initial',
             'project': 'binutils',
             'stage': 'cross-initial',
             'recipe': 'binutils/stages/cross-initial'},
            {'id': 'gcc-cross-initial',
             'project': 'gcc',
             'stage': 'cross-initial',
             'recipe': 'gcc/stages/cross-initial'},
            {'id': 'linux-api-headers',
             'project': 'linux',
             'stage': 'api-headers',
             'recipe': 'linux/stages/api-headers'},
            {'id': 'glibc-cross-initial',
             'project': 'glibc',
             'stage': 'cross-initial',
             'recipe': 'glibc/stages/cross-initial'}],
 'targets': ['binutils-cross-initial', 'gcc-cross-initial', 'linux-api-headers', 'glibc-cross-initial']}
