# Data only; parsed with ast.literal_eval.
{'schema': 1,
 'lfs_edition': '13.1-systemd',
 'architecture': 'x86_64',
 'target': 'x86_64-zog-linux-gnu',
 'stages': [{'id': 'gcc-temporary-libstdcpp',
             'project': 'gcc',
             'stage': 'temporary-libstdcpp',
             'recipe': 'gcc/stages/temporary-libstdcpp'},
            {'id': 'm4-temporary',
             'project': 'm4',
             'stage': 'temporary',
             'recipe': 'm4/stages/temporary'},
            {'id': 'ncurses-temporary',
             'project': 'ncurses',
             'stage': 'temporary',
             'recipe': 'ncurses/stages/temporary'},
            {'id': 'bash-temporary',
             'project': 'bash',
             'stage': 'temporary',
             'recipe': 'bash/stages/temporary'},
            {'id': 'coreutils-temporary',
             'project': 'coreutils',
             'stage': 'temporary',
             'recipe': 'coreutils/stages/temporary'},
            {'id': 'diffutils-temporary',
             'project': 'diffutils',
             'stage': 'temporary',
             'recipe': 'diffutils/stages/temporary'},
            {'id': 'file-temporary',
             'project': 'file',
             'stage': 'temporary',
             'recipe': 'file/stages/temporary'},
            {'id': 'findutils-temporary',
             'project': 'findutils',
             'stage': 'temporary',
             'recipe': 'findutils/stages/temporary'},
            {'id': 'gawk-temporary',
             'project': 'gawk',
             'stage': 'temporary',
             'recipe': 'gawk/stages/temporary'},
            {'id': 'grep-temporary',
             'project': 'grep',
             'stage': 'temporary',
             'recipe': 'grep/stages/temporary'},
            {'id': 'gzip-temporary',
             'project': 'gzip',
             'stage': 'temporary',
             'recipe': 'gzip/stages/temporary'},
            {'id': 'make-temporary',
             'project': 'make',
             'stage': 'temporary',
             'recipe': 'make/stages/temporary'},
            {'id': 'patch-temporary',
             'project': 'patch',
             'stage': 'temporary',
             'recipe': 'patch/stages/temporary'},
            {'id': 'sed-temporary',
             'project': 'sed',
             'stage': 'temporary',
             'recipe': 'sed/stages/temporary'},
            {'id': 'tar-temporary',
             'project': 'tar',
             'stage': 'temporary',
             'recipe': 'tar/stages/temporary'},
            {'id': 'xz-temporary',
             'project': 'xz',
             'stage': 'temporary',
             'recipe': 'xz/stages/temporary'}],
 'targets': ['gcc-temporary-libstdcpp',
             'm4-temporary',
             'ncurses-temporary',
             'bash-temporary',
             'coreutils-temporary',
             'diffutils-temporary',
             'file-temporary',
             'findutils-temporary',
             'gawk-temporary',
             'grep-temporary',
             'gzip-temporary',
             'make-temporary',
             'patch-temporary',
             'sed-temporary',
             'tar-temporary',
             'xz-temporary']}
