# Data only; parsed with ast.literal_eval.
{'schema': 1,
 'architecture': 'x86_64',
 'lfs_edition': '13.1-systemd',
 'stages': [{'id': 'bzip2-final',
             'project': 'bzip2',
             'recipe': 'bzip2/stages/final',
             'stage': 'final'},
            {'id': 'flex-final',
             'project': 'flex',
             'recipe': 'flex/stages/final',
             'stage': 'final'},
            {'id': 'bc-final',
             'project': 'bc',
             'recipe': 'bc/stages/final',
             'stage': 'final'},
            {'id': 'binutils-final',
             'project': 'binutils',
             'recipe': 'binutils/stages/final',
             'stage': 'final'}],
 'targets': ['binutils-final', 'bzip2-final', 'flex-final', 'bc-final']}
