{'architecture': 'x86_64',
 'lfs_edition': '13.1-systemd',
 'schema': 1,
 'stages': [{'id': 'gmp-final',
             'project': 'gmp',
             'recipe': 'gmp/stages/final',
             'stage': 'final'},
            {'id': 'mpfr-final',
             'project': 'mpfr',
             'recipe': 'mpfr/stages/final',
             'stage': 'final'},
            {'id': 'mpc-final',
             'project': 'mpc',
             'recipe': 'mpc/stages/final',
             'stage': 'final'}],
 'targets': ['mpc-final']}
