# Data only; parsed with ast.literal_eval.
{'schema': 1,
 'lfs_edition': '13.1-systemd',
 'architecture': 'x86_64',
 'target': 'x86_64-zog-linux-gnu',
 'stages': [{'id': 'gettext-native-environment',
             'project': 'gettext',
             'stage': 'native-environment',
             'recipe': 'gettext/stages/native-environment'},
            {'id': 'bison-native-environment',
             'project': 'bison',
             'stage': 'native-environment',
             'recipe': 'bison/stages/native-environment'},
            {'id': 'perl-native-environment',
             'project': 'perl',
             'stage': 'native-environment',
             'recipe': 'perl/stages/native-environment'},
            {'id': 'zlib-native-environment',
             'project': 'zlib',
             'stage': 'native-environment',
             'recipe': 'zlib/stages/native-environment'},
            {'id': 'mpdecimal-native-environment',
             'project': 'mpdecimal',
             'stage': 'native-environment',
             'recipe': 'mpdecimal/stages/native-environment'},
            {'id': 'python-native-environment',
             'project': 'python',
             'stage': 'native-environment',
             'recipe': 'python/stages/native-environment'},
            {'id': 'texinfo-native-environment',
             'project': 'texinfo',
             'stage': 'native-environment',
             'recipe': 'texinfo/stages/native-environment'},
            {'id': 'util-linux-native-environment',
             'project': 'util-linux',
             'stage': 'native-environment',
             'recipe': 'util-linux/stages/native-environment'}],
 'targets': ['gettext-native-environment',
             'bison-native-environment',
             'perl-native-environment',
             'zlib-native-environment',
             'mpdecimal-native-environment',
             'python-native-environment',
             'texinfo-native-environment',
             'util-linux-native-environment']}
