# Data only; parsed with ast.literal_eval.
{'schema': 1,
 'architecture': 'x86_64',
 'stages': [{'id': 'python-flit-core-final',
             'project': 'python-flit-core',
             'stage': 'final',
             'recipe': 'python-flit-core/stages/final'},
            {'id': 'python-installer-final',
             'project': 'python-installer',
             'stage': 'final',
             'recipe': 'python-installer/stages/final'},
            {'id': 'python-setuptools-final',
             'project': 'python-setuptools',
             'stage': 'final',
             'recipe': 'python-setuptools/stages/final'},
            {'id': 'python-wheel-final',
             'project': 'python-wheel',
             'stage': 'final',
             'recipe': 'python-wheel/stages/final'},
            {'id': 'python-packaging-final',
             'project': 'python-packaging',
             'stage': 'final',
             'recipe': 'python-packaging/stages/final'},
            {'id': 'python-hatchling-final',
             'project': 'python-hatchling',
             'stage': 'final',
             'recipe': 'python-hatchling/stages/final'},
            {'id': 'python-hatch-vcs-final',
             'project': 'python-hatch-vcs',
             'stage': 'final',
             'recipe': 'python-hatch-vcs/stages/final'},
            {'id': 'python-setuptools-scm-final',
             'project': 'python-setuptools-scm',
             'stage': 'final',
             'recipe': 'python-setuptools-scm/stages/final'},
            {'id': 'python-pathspec-final',
             'project': 'python-pathspec',
             'stage': 'final',
             'recipe': 'python-pathspec/stages/final'},
            {'id': 'python-pluggy-final',
             'project': 'python-pluggy',
             'stage': 'final',
             'recipe': 'python-pluggy/stages/final'},
            {'id': 'python-trove-classifiers-final',
             'project': 'python-trove-classifiers',
             'stage': 'final',
             'recipe': 'python-trove-classifiers/stages/final'},
            {'id': 'python-tomlkit-final',
             'project': 'python-tomlkit',
             'stage': 'final',
             'recipe': 'python-tomlkit/stages/final'},
            {'id': 'python-vcs-versioning-final',
             'project': 'python-vcs-versioning',
             'stage': 'final',
             'recipe': 'python-vcs-versioning/stages/final'},
            {'id': 'python-calver-final',
             'project': 'python-calver',
             'stage': 'final',
             'recipe': 'python-calver/stages/final'},
            {'id': 'python-poetry-core-final',
             'project': 'python-poetry-core',
             'stage': 'final',
             'recipe': 'python-poetry-core/stages/final'},
            {'id': 'python-certifi-final',
             'project': 'python-certifi',
             'stage': 'final',
             'recipe': 'python-certifi/stages/final'},
            {'id': 'python-cffi-final',
             'project': 'python-cffi',
             'stage': 'final',
             'recipe': 'python-cffi/stages/final'},
            {'id': 'python-charset-normalizer-final',
             'project': 'python-charset-normalizer',
             'stage': 'final',
             'recipe': 'python-charset-normalizer/stages/final'},
            {'id': 'python-idna-final',
             'project': 'python-idna',
             'stage': 'final',
             'recipe': 'python-idna/stages/final'},
            {'id': 'python-pycparser-final',
             'project': 'python-pycparser',
             'stage': 'final',
             'recipe': 'python-pycparser/stages/final'},
            {'id': 'python-pyjwt-final',
             'project': 'python-pyjwt',
             'stage': 'final',
             'recipe': 'python-pyjwt/stages/final'},
            {'id': 'python-requests-final',
             'project': 'python-requests',
             'stage': 'final',
             'recipe': 'python-requests/stages/final'},
            {'id': 'python-typing-extensions-final',
             'project': 'python-typing-extensions',
             'stage': 'final',
             'recipe': 'python-typing-extensions/stages/final'},
            {'id': 'python-urllib3-final',
             'project': 'python-urllib3',
             'stage': 'final',
             'recipe': 'python-urllib3/stages/final'}],
 'targets': ['python-flit-core-final',
             'python-installer-final',
             'python-setuptools-final',
             'python-wheel-final',
             'python-packaging-final',
             'python-hatchling-final',
             'python-hatch-vcs-final',
             'python-setuptools-scm-final',
             'python-pathspec-final',
             'python-pluggy-final',
             'python-trove-classifiers-final',
             'python-tomlkit-final',
             'python-vcs-versioning-final',
             'python-calver-final',
             'python-poetry-core-final',
             'python-certifi-final',
             'python-cffi-final',
             'python-charset-normalizer-final',
             'python-idna-final',
             'python-pycparser-final',
             'python-pyjwt-final',
             'python-requests-final',
             'python-typing-extensions-final',
             'python-urllib3-final']}
