# Data only; parsed with ast.literal_eval.
{'schema': 1,
 'architecture': 'x86_64',
 'stages': [{'id': 'libffi-final',
             'project': 'libffi',
             'stage': 'final',
             'recipe': 'libffi/stages/final'},
            {'id': 'expat-final',
             'project': 'expat',
             'stage': 'final',
             'recipe': 'expat/stages/final'},
            {'id': 'gdbm-final',
             'project': 'gdbm',
             'stage': 'final',
             'recipe': 'gdbm/stages/final'},
            {'id': 'pkgconf-final',
             'project': 'pkgconf',
             'stage': 'final',
             'recipe': 'pkgconf/stages/final'},
            {'id': 'python-final',
             'project': 'python',
             'stage': 'final',
             'recipe': 'python/stages/final'}],
 'targets': ['python-final']}
