# Data only; parsed with ast.literal_eval.
{'schema': 1,
 'architecture': 'x86_64',
 'stages': [{'id': 'attr-final',
             'project': 'attr',
             'stage': 'final',
             'recipe': 'attr/stages/final'},
            {'id': 'acl-test-bootstrap',
             'project': 'acl',
             'stage': 'test-bootstrap',
             'recipe': 'acl/stages/test-bootstrap'},
            {'id': 'coreutils-acl-test-tools',
             'project': 'coreutils',
             'stage': 'acl-test-tools',
             'recipe': 'coreutils/stages/acl-test-tools'},
            {'id': 'acl-final', 'project': 'acl', 'stage': 'final', 'recipe': 'acl/stages/final'},
            {'id': 'libxcrypt-final',
             'project': 'libxcrypt',
             'stage': 'final',
             'recipe': 'libxcrypt/stages/final'},
            {'id': 'lz4-final', 'project': 'lz4', 'stage': 'final', 'recipe': 'lz4/stages/final'},
            {'id': 'pcre2-final',
             'project': 'pcre2',
             'stage': 'final',
             'recipe': 'pcre2/stages/final'},
            {'id': 'kmod-final',
             'project': 'kmod',
             'stage': 'final',
             'recipe': 'kmod/stages/final'}],
 'targets': ['attr-final',
             'acl-final',
             'libxcrypt-final',
             'lz4-final',
             'pcre2-final',
             'kmod-final']}
