# Data only; read with ast.literal_eval.
{'schema': 1,
 'version': '7.1.8',
 'homepage': 'https://www.kernel.org/',
 'repository_url': None,
 'repository_status': 'not-recorded',
 'release_url': 'https://www.kernel.org/pub/linux/kernel/v7.x/linux-7.1.8.tar.xz',
 'sha256': 'ff01dcb449279d5b4cfccdb01fee639cf5ff1803f1749a77844dd33915422c49',
 'verification_status': 'https-download-and-lfs-md5-compared',
 'reference': 'https://www.linuxfromscratch.org/lfs/view/13.1-systemd/chapter03/packages.html',
 'secondary_mirrors': [{'url': 'https://github.com/gregkh/linux',
                        'kind': 'git-repository',
                        'role': 'stable-tree-mirror',
                        'automatic_fallback': False,
                        'release_archive_equivalence': 'not-asserted'},
                       {'url': 'https://github.com/torvalds/linux',
                        'kind': 'git-repository',
                        'automatic_fallback': False,
                        'release_archive_equivalence': 'not-asserted'}],
 'mirror_status': 'listed'}
