from importlib import import_module
from typing import Protocol

from django.conf import settings

from .types import ApplicationSummary, RuntimeSummary


class BoxControlUnavailable(RuntimeError):
    pass


class BoxControlGateway(Protocol):
    """Narrow station-access projection of box-control's trusted in-process API."""

    def workspace_capabilities(self) -> dict: ...
    def require_workspace_contract(self) -> dict: ...
    def register_workspace(self, workspace) -> dict: ...
    def workspace_membership(self, workspace_id: str) -> list[dict]: ...
    def workspace_catalogue(self) -> list[dict]: ...
    def workspace_desktop_access(self, workspace_id: str) -> dict: ...
    def delete_registered_workspace(self, workspace_id: str) -> dict: ...
    def preflight_workspace_application(self, name: str, workspace_id: str) -> dict: ...
    def get_current_runtime(self, runtime_id: str) -> RuntimeSummary | None: ...
    def list_applications(self) -> tuple[ApplicationSummary, ...]: ...
    def workspace_application_runtimes(self, workspace_id: str) -> tuple[RuntimeSummary, ...]: ...

    def workspace_dependencies(self, workspace_id: str, *, excluding_runtime: str | None = None) -> list[str]: ...

    def list_runtimes(self) -> tuple[RuntimeSummary, ...]: ...
    def get_runtime(self, runtime_id: str) -> RuntimeSummary | None: ...
    def issue_application_request_id(self) -> str: ...
    def find_application_launch(self, application_name: str, *, request_id: str, workspace_id: str | None = None, parameters: dict | None = None) -> RuntimeSummary | None: ...
    def launch_application(self, application_name: str, *, request_id: str, workspace_id: str | None = None, parameters: dict | None = None) -> RuntimeSummary: ...
    def read_logs(self, runtime_id: str, *, program: str | None = None, cursor: str | None = None, limit: int = 200): ...
    def cancel_application_launch(self, application_name: str, *, request_id: str, workspace_id: str | None = None, parameters: dict | None = None) -> dict: ...
    def terminate_application_runtime(self, runtime_id: str) -> RuntimeSummary: ...


def _import_factory(path: str):
    module_name, separator, attribute = path.partition(":")
    if not separator:
        raise BoxControlUnavailable("gateway factory must use module:function syntax")
    try:
        module = import_module(module_name)
        return getattr(module, attribute)
    except (ImportError, AttributeError) as exc:
        raise BoxControlUnavailable(f"cannot load box-control gateway factory {path}: {exc}") from exc


def get_gateway() -> BoxControlGateway:
    return _import_factory(settings.STATION_ACCESS_BOX_CONTROL_GATEWAY_FACTORY)()
