# Data only; parsed with ast.literal_eval.
{'schema': 1,
 'specs': [{'url': 'https://src.fedoraproject.org/rpms/python3.14/raw/rawhide/f/python3.14.spec',
            'retrieved': '2026-10-03',
            'sha256': 'c9c377c0aedfe6257a2a97b0669ce5e0293df26fd10c481373a77a44e009efbc',
            'build_requires': ['BuildRequires: autoconf',
                               'BuildRequires: bluez-libs-devel',
                               'BuildRequires: bzip2-devel',
                               'BuildRequires: expat-devel >= 2.5.0-2',
                               'BuildRequires: findutils',
                               'BuildRequires: gcc',
                               'BuildRequires: gdbm-devel',
                               'BuildRequires: git-core',
                               'BuildRequires: glibc-devel',
                               'BuildRequires: gnupg2',
                               'BuildRequires: libX11-devel',
                               'BuildRequires: libffi-devel',
                               'BuildRequires: libuuid-devel',
                               'BuildRequires: libzstd-devel',
                               'BuildRequires: make',
                               'BuildRequires: mpdecimal-devel',
                               'BuildRequires: ncurses-devel',
                               'BuildRequires: pkgconfig',
                               'BuildRequires: python-rpm-macros',
                               'BuildRequires: readline-devel',
                               'BuildRequires: redhat-rpm-config >= 127',
                               'BuildRequires: sqlite-devel',
                               'BuildRequires: systemtap-sdt-devel',
                               'BuildRequires: tcl-devel',
                               'BuildRequires: tk-devel',
                               'BuildRequires: xz-devel',
                               'BuildRequires: zlib-devel',
                               'BuildRequires: /usr/bin/dtrace',
                               'BuildRequires: (openssl-devel < 1:4 or openssl3-devel)',
                               'BuildRequires: gcc-c++',
                               'BuildRequires: gdb',
                               'BuildRequires: glibc-all-langpacks',
                               'BuildRequires: tzdata',
                               'BuildRequires: clang(major) = 19',
                               'BuildRequires: llvm(major) = 19',
                               'BuildRequires: valgrind-devel',
                               'BuildRequires: desktop-file-utils',
                               'BuildRequires: libappstream-glib',
                               'BuildRequires: %{python_wheel_pkg_prefix}-pip-wheel >= 23.1.2',
                               'BuildRequires: %{python_wheel_pkg_prefix}-setuptools-wheel',
                               'BuildRequires: (%{python_wheel_pkg_prefix}-wheel-wheel if '
                               '%{python_wheel_pkg_prefix}-setuptools-wheel < 71)',
                               'BuildRequires: python%{pybasever}',
                               'BuildRequires: python3-rpm-generators'],
            'patch_inventory': ['Patch251: 00251-change-user-install-location.patch',
                                'Patch466: '
                                '00466-downstream-only-lower-xml_combined_version-threshold-for-reparse-deferral.patch',
                                'Patch475: 00475-cve-2025-15367.patch',
                                'Patch477: '
                                '00477-raise-an-error-when-importing-stdlib-modules-compiled-for-a-different-python-version.patch',
                                'Patch486: '
                                '00486-gh-148646-add---enable-prebuilt-jit-stencils-configure-flag.patch']},
           {'url': 'https://src.fedoraproject.org/rpms/python3.15/raw/rawhide/f/python3.15.spec',
            'retrieved': '2026-10-03',
            'sha256': '07295b5a37469eb9b1602a2ebd891659725fc07a663def136c4ce74ebf2fc6b9',
            'build_requires': ['BuildRequires: autoconf',
                               'BuildRequires: bluez-libs-devel',
                               'BuildRequires: bzip2-devel',
                               'BuildRequires: expat-devel >= 2.5.0-2',
                               'BuildRequires: findutils',
                               'BuildRequires: gcc',
                               'BuildRequires: gdbm-devel',
                               'BuildRequires: git-core',
                               'BuildRequires: glibc-devel',
                               'BuildRequires: gnupg2',
                               'BuildRequires: libX11-devel',
                               'BuildRequires: libffi-devel',
                               'BuildRequires: libuuid-devel',
                               'BuildRequires: libzstd-devel',
                               'BuildRequires: make',
                               'BuildRequires: mpdecimal-devel',
                               'BuildRequires: ncurses-devel',
                               'BuildRequires: openssl-devel',
                               'BuildRequires: pkgconfig',
                               'BuildRequires: python-rpm-macros',
                               'BuildRequires: readline-devel',
                               'BuildRequires: redhat-rpm-config >= 127',
                               'BuildRequires: sqlite-devel',
                               'BuildRequires: systemtap-sdt-devel',
                               'BuildRequires: tcl-devel',
                               'BuildRequires: tk-devel',
                               'BuildRequires: xz-devel',
                               'BuildRequires: zlib-devel',
                               'BuildRequires: /usr/bin/dtrace',
                               'BuildRequires: gcc-c++',
                               'BuildRequires: gdb',
                               'BuildRequires: glibc-all-langpacks',
                               'BuildRequires: tzdata',
                               'BuildRequires: clang(major) = 21',
                               'BuildRequires: llvm(major) = 21',
                               'BuildRequires: clang >= 19',
                               'BuildRequires: llvm >= 19',
                               'BuildRequires: valgrind-devel',
                               'BuildRequires: desktop-file-utils',
                               'BuildRequires: libappstream-glib',
                               'BuildRequires: %{python_wheel_pkg_prefix}-pip-wheel >= 23.1.2',
                               'BuildRequires: %{python_wheel_pkg_prefix}-setuptools-wheel',
                               'BuildRequires: (%{python_wheel_pkg_prefix}-wheel-wheel if '
                               '%{python_wheel_pkg_prefix}-setuptools-wheel < 71)',
                               'BuildRequires: python%{pybasever}',
                               'BuildRequires: python3-rpm-generators'],
            'patch_inventory': ['Patch251: 00251-change-user-install-location.patch',
                                'Patch466: '
                                '00466-downstream-only-lower-xml_combined_version-threshold-for-reparse-deferral.patch',
                                'Patch486: '
                                '00486-gh-148646-add---enable-prebuilt-jit-stencils-configure-flag.patch']},
           {'url': 'https://api.opensuse.org/public/source/openSUSE:Factory/python314/python314.spec',
            'retrieved': '2026-10-03',
            'sha256': '048021ede41c0f2810d1b43a88460dfdcfb46624525becd25925d262b318debd',
            'build_requires': ['BuildRequires:  autoconf-archive',
                               'BuildRequires:  automake',
                               'BuildRequires:  crypto-policies-scripts',
                               'BuildRequires:  fdupes',
                               'BuildRequires:  gcc',
                               'BuildRequires:  gcc-c++',
                               'BuildRequires:  gmp-devel',
                               'BuildRequires:  lzma-devel',
                               'BuildRequires:  netcfg',
                               'BuildRequires:  openssl-devel',
                               'BuildRequires:  pkgconfig',
                               'BuildRequires:  xz',
                               'BuildRequires:  pkgconfig(bzip2)',
                               'BuildRequires:  pkgconfig(expat)',
                               'BuildRequires:  pkgconfig(libffi)',
                               'BuildRequires:  pkgconfig(libzstd)',
                               'BuildRequires:  pkgconfig(uuid)',
                               'BuildRequires:  pkgconfig(zlib)',
                               'BuildRequires:  rpm-build-python',
                               'BuildRequires:  pkgconfig(libnsl)',
                               'BuildRequires:  pkgconfig(libtirpc)',
                               'BuildRequires:  mpdecimal-devel',
                               'BuildRequires:  python311-Sphinx',
                               'BuildRequires:  python311-python-docs-theme',
                               'BuildRequires:  python3-Sphinx >= 4.0.0',
                               'BuildRequires:  python3-python-docs-theme >= 2022.1',
                               'BuildRequires:  clang21 llvm21',
                               'BuildRequires:  llvm',
                               'BuildRequires:  appstream-glib',
                               'BuildRequires:  gcc-c++',
                               'BuildRequires:  gdbm-devel',
                               'BuildRequires:  gettext',
                               'BuildRequires:  readline-devel',
                               'BuildRequires:  sqlite-devel',
                               'BuildRequires:  timezone',
                               'BuildRequires:  pkgconfig(ncurses)',
                               'BuildRequires:  pkgconfig(tk)',
                               'BuildRequires:  pkgconfig(x11)'],
            'patch_inventory': ['Patch02:        F00251-change-user-install-location.patch',
                                'Patch03:        python-3.3.0b1-localpath.patch',
                                'Patch04:        python-3.3.0b1-fix_date_time_compiler.patch',
                                'Patch05:        configure-drop-autoconf-ver-req.patch',
                                'Patch07:        bpo-31046_ensurepip_honours_prefix.patch',
                                'Patch09:        skip-test_pyobject_freed_is_freed.patch',
                                'Patch39:        CVE-2023-52425-libexpat-2.6.0-backport-15.6.patch',
                                'Patch40:        fix-test-recursion-limit-15.6.patch',
                                'Patch41:        bsc1243155-sphinx-non-determinism.patch',
                                'Patch45:        gh139257-Support-docutils-0.22.patch',
                                'Patch46:        CVE-2024-6923-follow-up-EOL-email-headers.patch',
                                'Patch49:        CVE-2025-12781-b64decode-alt-chars.patch',
                                'Patch51:        CVE-2025-15367-poplib-ctrl-chars.patch',
                                'Patch57:        bsc1260884-llvm21-support.patch',
                                'Patch58:        CVE-2026-17084-stringprep-rfc3454.patch',
                                'Patch59:        CVE-2026-19672-tarfile-outside-dirs.patch',
                                'Patch60:         CVE-2026-15310-bound-zipfile-decompression.patch',
                                'Patch61:         '
                                'CVE-2026-15310-keep-through-3rd-party-decomp.patch']}],
 'decisions': {'source': 'Final 3.15.0rc2 fixes removed OpenSSL 4 methods upstream; retain 3.14.7 '
                         'bootstrap separately. No local Python patch.',
               'added_source_dependencies': ['libffi', 'expat', 'gdbm', 'pkgconf'],
               'base_dependencies': ['gcc',
                                     'glibc',
                                     'make',
                                     'findutils',
                                     'bzip2',
                                     'xz',
                                     'zlib',
                                     'zstd',
                                     'mpdecimal',
                                     'ncurses',
                                     'util-linux',
                                     'readline',
                                     'openssl',
                                     'sqlite',
                                     'tcl',
                                     'dejagnu',
                                     'expect'],
               'enabled': ['shared libpython',
                           'system expat/libffi/mpdecimal',
                           'SQLite loadable extensions',
                           'OpenSSL cipher policy',
                           'PGO',
                           'LTO',
                           'IPv6',
                           'GIL build'],
               'deferred': ['Tk/X11/IDLE GUI',
                            'Bluetooth headers',
                            'dtrace/systemtap',
                            'Valgrind',
                            'GDB integration matrix',
                            'LLVM/JIT/free-threaded variants',
                            'public CA trust data',
                            'timezone database packaging',
                            'Sphinx documentation builds',
                            'RPM macros/wheels/install layouts',
                            'full release regression suite'],
               'test_scope': 'Required runtime module regressions plus installed offline HTTPS '
                             'positive/wrong-host/untrusted CA and SQLite persistence; not full '
                             'distribution matrix.',
               'patch_review': 'Patch inventories inspected; downstream install paths, distro '
                               'Expat backport thresholds, JIT prebuilt stencil options, docs and '
                               'older-series security backports are not copied. This is not a CVE '
                               'audit or claim that every distro patch is redundant.',
               'pkgconf_testing': 'Pinned 3.0.5 uses its own C test runner: make check, no Kyua '
                                  'dependency.'}}
